version: '3.0'

services:
  postgres:
    image: postgres:13.2
    ports:
      - 5432:5432
    hostname: postgres
    container_name: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
    networks:
      - proxynet
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  proxynet:
    name: custom_network

volumes:
  pgdata:
